--liquibase formatted sql
--changeset dka:2025-01-29 objectQuotingStrategy="QUOTE_ALL_OBJECTS" failOnError: true

CREATE TABLE IF NOT EXISTS owners
(
    id_owners                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name_owners         VARCHAR(30),
    first_name_owners        VARCHAR(15)                             NOT NULL,
    middle_name_owners       VARCHAR(15),
    main_phone_owners        VARCHAR(16)                             NOT NULL,
    optional_phone_owners    VARCHAR(16),
    other_contacts_owners    VARCHAR(500),
    actual_address_owners    VARCHAR(150),
    trusted_man_owners       VARCHAR(150),
    comment_owners           VARCHAR(150),
    source_owners            VARCHAR(100),
    rating_owners            INTEGER,
    registration_date_owners TIMESTAMP                               NOT NULL,

    CONSTRAINT pk_owner PRIMARY KEY (id_owners),
    CONSTRAINT UQ_OWNER_MAIN_PHONE UNIQUE (main_phone_owners)
);