--liquibase formatted sql
--changeset mva:2025-01-29 objectQuotingStrategy="QUOTE_ALL_OBJECTS" failOnError: true

CREATE TABLE IF NOT EXISTS rooms
(
    id_rooms          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_rooms      VARCHAR(100)                            NOT NULL,
    area_rooms        REAL,
    category_id_rooms BIGINT,
    description_rooms VARCHAR(250),
    visible_rooms     BOOLEAN DEFAULT TRUE,
    CONSTRAINT pk_rooms PRIMARY KEY (id_rooms),
    CONSTRAINT fk_cat_to_rooms FOREIGN KEY (category_id_rooms) REFERENCES categories (id_categories) ON DELETE RESTRICT,
    CONSTRAINT UQ_ROOM_NUMBER UNIQUE (number_rooms),
    CONSTRAINT positive_room_area CHECK (area_rooms >= 0)
);