--liquibase formatted sql
--changeset dka:2025-01-29 objectQuotingStrategy="QUOTE_ALL_OBJECTS" failOnError: true

CREATE TABLE IF NOT EXISTS bookings
(
    id_bookings                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_bookings              VARCHAR(150)      NOT NULL,
    check_in_date_bookings     DATE                                    NOT NULL,
    check_out_date_bookings    DATE                                    NOT NULL,
    check_in_time_bookings     TIME,
    check_out_time_bookings    TIME,
    status_bookings            VARCHAR(150)      NOT NULL,
    reason_of_stop_bookings    VARCHAR(150),
    reason_of_cancel_bookings  VARCHAR(150),
    price_bookings             REAL    DEFAULT 0 NOT NULL,
    amount_bookings            REAL    DEFAULT 0 NOT NULL,
    prepayment_amount_bookings REAL    DEFAULT 0 NOT NULL,
    made_prepayment_bookings   BOOLEAN DEFAULT FALSE,
    comment_bookings           VARCHAR(150),
    file_bookings              VARCHAR(150),
    room_id_bookings           BIGINT,
    CONSTRAINT pk_bookings PRIMARY KEY (id_bookings),
    CONSTRAINT fk_room_to_bookings FOREIGN KEY (room_id_bookings) REFERENCES rooms (id_rooms) ON DELETE RESTRICT,
    CONSTRAINT positive_price_bookings CHECK (price_bookings >= 0),
    CONSTRAINT positive_amount_bookings CHECK (amount_bookings >= 0),
    CONSTRAINT positive_prepayment_amount_bookings CHECK (prepayment_amount_bookings >= 0),
    CONSTRAINT check_out_later_than_in CHECK (check_out_date_bookings >= check_in_date_bookings)
);