--liquibase formatted sql
--changeset dka:2025-01-29 objectQuotingStrategy="QUOTE_ALL_OBJECTS" failOnError: true

CREATE TABLE IF NOT EXISTS categories
(
    id_categories          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_categories        VARCHAR(20)                             NOT NULL,
    description_categories VARCHAR(250),
    CONSTRAINT pk_categories PRIMARY KEY (id_categories),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name_categories)
);