--liquibase formatted sql
--changeset dka:2025-01-29 objectQuotingStrategy="QUOTE_ALL_OBJECTS" failOnError: true

CREATE TABLE IF NOT EXISTS users
(
    id_users          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name_users   VARCHAR(30),
    first_name_users  VARCHAR(15)                             NOT NULL,
    middle_name_users VARCHAR(15),
    email_users       VARCHAR(254)                            NOT NULL,
    password_users    VARCHAR(10),
    role_users        VARCHAR(16)                             NOT NULL,
    active_users      BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id_users),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email_users)
);