name: Build application
on:
  workflow_dispatch:

jobs:
  docker:
    name: Build Docker Image
    uses: Modgy/modgy-ci-cd/.github/workflows/publish_docker_image.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
