name: Update application
on:
  workflow_dispatch:

jobs:
  docker:
    name: Build Docker Image
    uses: Modgy/modgy-ci-cd/.github/workflows/update_service.yml@workflow/service-update
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
    with:
      DOCKER_SERVICE: back
